-- Migration: Update embedding dimension from 1024 to 384
-- Required for: multilingual-e5-small model
-- Date: 2025-12-30
--
-- IMPORTANT: Run this migration if you're using multilingual-e5-small
-- If you already have embeddings with 1024D, you'll need to:
-- 1. Clear existing embeddings first
-- 2. Run this migration
-- 3. Re-index documents

-- Step 1: Drop existing HNSW index (required before column change)
DROP INDEX IF EXISTS idx_embeddings_vector;

-- Step 2: Alter the embedding column dimension
-- Note: This will fail if there are existing embeddings with different dimensions
ALTER TABLE public.document_embeddings
ALTER COLUMN embedding TYPE vector(384);

-- Step 3: Recreate HNSW index with new dimension
CREATE INDEX idx_embeddings_vector
    ON public.document_embeddings
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- Step 4: Update the match_documents function for 384D
DROP FUNCTION IF EXISTS match_documents(vector, float, int, text);

CREATE OR REPLACE FUNCTION match_documents(
    query_embedding vector(384),
    match_threshold float DEFAULT 0.5,
    match_count int DEFAULT 10,
    filter_commodity text DEFAULT NULL
)
RETURNS TABLE (
    id UUID,
    document_id UUID,
    chunk_index INTEGER,
    chunk_text TEXT,
    metadata JSONB,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        document_embeddings.id,
        document_embeddings.document_id,
        document_embeddings.chunk_index,
        document_embeddings.chunk_text,
        document_embeddings.metadata,
        1 - (document_embeddings.embedding <=> query_embedding) AS similarity
    FROM document_embeddings
    WHERE
        1 - (document_embeddings.embedding <=> query_embedding) > match_threshold
        AND (
            filter_commodity IS NULL
            OR document_embeddings.metadata->>'commodity' = filter_commodity
        )
    ORDER BY document_embeddings.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- Grant permissions
GRANT EXECUTE ON FUNCTION match_documents TO anon;
GRANT EXECUTE ON FUNCTION match_documents TO authenticated;

-- Update comments
COMMENT ON COLUMN public.document_embeddings.embedding IS
'Vector embedding (384 dimensions) generated by multilingual-e5-small model.';

COMMENT ON FUNCTION match_documents IS
'Semantic search function using cosine similarity. Returns top K chunks above threshold for 384D embeddings.';

-- Verify
DO $$
BEGIN
    RAISE NOTICE 'Migration complete: embedding dimension updated to 384D for multilingual-e5-small';
END $$;
